### ISSUE TITLE
Question 5

### ISSUE THREAD

**Issue by JMukta25** [Google-Developer-Student-Club-CCOEW/Competitive-Coding#5] opened 2022-10-12 17:51 UTC
Paheli has a string S with her. Paheli will win if the string contains a contiguous substring of length strictly greater than 3 in which all its characters are vowels.

Check if Paheli won or not.

Note that, in english alphabet, vowels are a, e, i, o, and u.
Input Format-
Each test case contains of a single line of input, a string S.
Output Format-For each test case, if Paheli is happy, print WINNER else print LOSER.
.Constraints
1≤T≤1000
3 <= |S| <= 1000, where |S| is the length of S.
S will only contain lowercase English letters.
 Sampel Input n=4
aeiou
abxy
aebcdefghij
abcdeeaifg
Output-WINNER
LOSER
LOSER
WINNER

**Comment by GayatriChaudhari1281** [comment] 2022-10-17 07:36
Name-Gayatri Chaudhari
College-Cummins college of engineering ,Pune
Department-Computer Department
I would like to work on this issue

**Comment by gaurijoshi22** [comment] 2022-10-17 08:43
Gauri Joshi
Cummins College of Engineering for Women, Pune
Dept- Information Technology
I would like to work on this issue

**Comment by JMukta25** [comment] 2022-10-17 14:20
> 


> Ojaswi Pande CCOEW SY COMP can you assign this issue to me?
This issue has been assigned to someone else already.

**Comment by GayatriChaudhari1281** [comment] 2022-10-17 18:24
@JMukta25 I have submitted the solution for this issue and it has been merged into main repository as well. Can you check once?

**Comment by ManasiGDeshmukh** [comment] 2022-10-18 15:49
Manasi Deshmukh
CCOEW
SY COMP
can you assign this issue to me?

**Comment by NikitaMiraje** [comment] 2022-10-22 13:52
Nikita Miraje
CCOEW
ENTC
I would like to work on this issue....can you assign me???

**Comment by pranotip283** [comment] 2022-10-23 14:08
Pranoti Patil
Comp
CCOEW
Can you assign this issue to me?

**Comment by gaurijoshi22** [comment] 2022-10-27 09:29
Gauri Joshi
Cummins College of Engineering for Women, Pune
Dept- SY-IT
If the issue is still open, I would like to work on this issue.
Please assign me this issue.

**Comment by NikitaMiraje** [comment] 2022-10-28 10:40
@JMukta25 if this issue is still open can you assign me???

**Closed** 2022-10-28 15:42 UTC
Labels: good first issue, easy, hacktoberfest
